name: "dict_model"
platform: "pytorch_libtorch"
max_batch_size: 8

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ 20 ]
  },
  {
    name: "embeddings"
    data_type: TYPE_FP32
    dims: [ 5 ]
  }
]
